name: Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1
      - run: git submodule update --init --recursive

      # Setup Node and the dependencies for PostCSS
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      # Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true

      # Build website with Hugo
      - name: Build
        run: HUGO_ENV="production" hugo --minify --gc

      # Deploy the website to gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'HGPBot'
          user_email: 'hgpbot@hervormdputten.nl'
          cname: app.hervormdputten.nl

